theme = "gruvbox"

[editor]
line-number = "relative"
scroll-lines = 1
auto-pairs = false
auto-save = true
cursorline = true
bufferline = "always"
true-color = true
undercurl = true
auto-completion = true
auto-info = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "╎", "┆", "┊"
skip-levels = 0

[editor.statusline]
# [#2869] file-type-icon
left = [
  "mode",
  "spinner",
  "version-control",
  "read-only-indicator",
  # "file-type-icon",
  "file-name",
  "file-modification-indicator",
]
center = ["diagnostics", "workspace-diagnostics"]
right = [
  "register",
  "selections",
  "primary-selection-length",
  "file-encoding",
  "file-line-ending",
  "position",
  "position-percentage",
  "file-type",
]
separator = "│"

[keys.normal]
"C-s" = ":write"
"C-j" = "save_selection"

[keys.normal.space]
"." = "file_picker_in_current_buffer_directory"
