[helix.files]
"helix/config.toml" = "~/AppData/Roaming/helix/config.toml"

[lazygit.files]
"lazygit/config.yml" = { target = "~/AppData/Local/lazygit/config.yml", type = "symbolic" }

[yazi.files]
"yazi/yazi.toml" = { target = "~/AppData/Roaming/yazi/config/yazi.toml", type = "symbolic" }

[nvim.files]
"nvim" = "~/AppData/Local/nvim"

[nushell.files]
"nushell" = "~/AppData/Roaming/nushell"