[helpers]
hello = ".dotter/helpers/hello.rhai"

# helix 配置-----------------------------------------------------
[helix]
depends = []

[helix.files]
"helix/config.toml" = "~/.config/helix/config.toml"

[helix.variables]

# wezterm 配置-----------------------------------------------------
[wezterm.files]
"wezterm" = "~/.config/wezterm"

# starship 配置-----------------------------------------------------
[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

# nushell 配置-----------------------------------------------------
[nushell.files]
"nushell" = "~/AppData/Roaming/nushell"

[settings]
default_target_type = "automatic"
