[helpers]
hello = ".dotter/helpers/hello.rhai"

# helix 配置-----------------------------------------------------
[helix]
depends = []

[helix.files]
"helix/config.toml" = "~/.config/helix/config.toml"

[helix.variables]

# wezterm 配置-----------------------------------------------------
[wezterm]
depends = []

[wezterm.files]
"wezterm" = "~/.config/wezterm"

[wezterm.variables]

[settings]
default_target_type = "automatic"
